import Head from 'next/head'
import Image from 'next/image'
import Footer from '../Components/Footer'
export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Angela Yu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=''>
      
      <div className="1st bg-blue-300 h-fit w-screen  text-center" >
        <div className="inner_1st_container pt-20">

        <img src="./img/cloud.png" alt="cloud img not found" className='relative left-2/3' />
        <h1 className='font-mono font-bold text-6xl m-10'>I'm Angela.</h1>
        <h2 className='font-mono font-bold text-3xl mb-8'>a <span className='underline'>pro</span>grammer.</h2>
        <img src="./img/cloud.png" alt="cloud img not found" className='relative left-72' />
        <img src="./img/mountain.png" alt="mountain img not found" className='mx-auto' />
        
        </div>
      </div>
      <div className="2nd  h-fit w-screen flex flex-col  ">
        <img  className='mt-16 w-32 h-32 mx-auto' src="./img/angela.png" alt="Angela img not found" />
        <h1 className='my-12 font-bold text-blue-300  cursor-pointer text-5xl flex mx-auto hover:text-blue-200' >Hello.</h1>
        <p className=' mb-20 flex mx-auto w-96 font-semibold text-lg text-gray-600 ' >I am an iOS and Web Developer. I'm the founder and CTO of The App Brewery. I ❤️ coffee and brew my own beers.</p>
        <hr className='border-dotted border-t-8 w-40  mx-auto hover:border-blue-300'   />
      </div>

      <div className="3rd flex h-fit   w-screen flex-col   ">
        <h1 className='text-center mt-24 font-mono font-bold text-5xl text-blue-300 hover:text-blue-200 cursor-pointer'>My Skills.</h1>
        <div className="3rd_inner_1st my-24 w-5/12 mx-auto">
            <img className='w-3/12  float-left mr-7'  src="https://media.giphy.com/media/3p50WGyUqeU5W/giphy.gif" alt="" />
            <h3 className='text-blue-300  font-serif hover:text-blue-200 cursor-pointer font-semibold text-lg'>Design & Development</h3>
             
            <p className='leading-8 font-serif font-medium text-base text-gray-600 '>I started learning to code when I was 12 years old because I wanted to make my own video games. Over time, I have gained a wealth of experience designing and developing mobile and web applications.</p>
          
        </div>
        <div className="3rd_inner_2nd w-5/12 mx-auto mb-20  ">
            <img className='w-3/12 float-left mr-7' src="./img/chillies.png" alt="" />
            <h3  className='text-blue-300  font-serif hover:text-blue-200 cursor-pointer font-semibold text-lg' >Hot Wings Challenge</h3>
            <p className='leading-8 font-serif font-medium text-base text-gray-600 '>But my best skill is actually in eating hot wings. I am the undisputed queen of hot wing challenges. Ghost Peppers and Carolina Reapers are my favourite snacks.</p>
        </div>
        <hr className='border-dotted border-t-8 w-40  mx-auto hover:border-blue-300'   />
      </div>
      <div className="4th my-16 text-center">
        <h1 className='font-serif font-bold text-5xl text-blue-300 hover:text-blue-200 cursor-pointer'>Get In Touch</h1>
        <h3 className='font-serif my-14 font-semibold text-2xl text-blue-300 cursor-pointer'>If you love hot wings as much as I do.</h3>
        <p className='font-serif w-2/5 mb-14 text-gray-600 mx-auto'>Love hot wings as much as I do? Let's talk about how awesome they are! We can code while we eat hot wings!</p>
        <button type="button" class="inline-block text-xl px-6 py-2.5 bg-blue-300 text-white font-medium  leading-tight uppercase rounded shadow-md hover:bg-blue-200 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out">Contact Me</button>
      </div>
      </main>

      <Footer/>
    </div>
  )
}
